CREATE TABLE "SCOTT"."VOL" 
   (	"NUMVOL" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"VILLE_DEPART" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"VILLE_ARRIVEE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"HEURE_DEPART" VARCHAR2(5 BYTE), 
	"HEURE_ARRIVEE" VARCHAR2(5 BYTE), 
	 CONSTRAINT "PK_VOL" PRIMARY KEY ("NUMVOL"));

CREATE TABLE "SCOTT"."PILOTE" 
   (	"MATRICULE" NUMBER NOT NULL ENABLE, 
	"NOM" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"VILLE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"AGE" NUMBER, 
	"SALAIRE" NUMBER, 
	 CONSTRAINT "PK_PILOTE" PRIMARY KEY ("MATRICULE"));

